# Generated by Django 3.2.6 on 2021-08-24 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_auto_20210824_2208'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='username',
            field=models.CharField(default='-', max_length=150),
            preserve_default=False,
        ),
    ]
