# Generated by Django 3.2.6 on 2021-08-26 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_userprofile_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='profile_img',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
