# Generated by Django 3.2.6 on 2021-08-27 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0009_auto_20210827_1356'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='friend',
        ),
    ]
