# Generated by Django 3.2.6 on 2021-08-27 20:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0016_alter_userprofile_friend'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('send_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations_sent', to='chat.userprofile')),
                ('send_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations_received', to='chat.userprofile')),
            ],
        ),
    ]
