# Generated by Django 3.2.6 on 2021-08-29 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0018_alter_userprofile_friend'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='friend',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='friends',
            field=models.ManyToManyField(blank=True, related_name='profiles_with_this_in_friends', to='chat.UserProfile'),
        ),
    ]
