# Generated by Django 3.2.6 on 2021-09-03 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0021_alter_room_last_message_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ('-last_message_at',)},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'ordering': ('username',)},
        ),
        migrations.AddField(
            model_name='userprofile',
            name='room_notifications',
            field=models.CharField(default='', max_length=255),
        ),
    ]
