# Generated by Django 3.2.6 on 2021-09-03 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0022_auto_20210903_2122'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='room_notifications',
        ),
    ]
