# Generated by Django 3.2.6 on 2021-09-04 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0023_remove_userprofile_room_notifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='rooms_notifications',
            field=models.CharField(default='', max_length=1024),
        ),
    ]
