# Generated by Django 3.2.6 on 2021-09-05 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0025_message_liked_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='rooms_notifications',
            field=models.CharField(blank=True, default='', max_length=1024),
        ),
    ]
